openapi: 3.0.1

info:
  title: REST-api
  description: A REST api that exposes services to GRDN apps
  version: 1.0.0

servers:
  - url: /grdn/api

tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

paths:

  /blockchain/castBallot:
    post:
      tags:
        - Blockchain
      description: Vote for a valid option of an election
      requestBody:
        description: Body needed to cast the ballot
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CastBallotRequest'  
        required: true
      responses:
        201:
          description: Ballot was casted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CastBallotResponse'     
        4XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /blockchain/registerVoter:
    post:
      tags:
        - Blockchain
      description: Register a new voter
      requestBody:
        description: New voter
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerVoter'     #TODO: Verify Schema
        required: true
      responses:
        201:
          description: Voter registered
          content:
            applicaction/json:
              schema:
                $ref: '#/components/schemas/Voter'       #TODO: Verify Schema
        4XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /blockchain/validateVoter:
    post:
      tags:
        - Blockchain
      description: Check if the voter can actually vote
      requestBody:
        description: Body needed to validate the voter
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateVoterRequest'
        required: true
      responses:
        201:
          description: Voter can vote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateVoterResponse'
        4XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vote/submitVote:
    post:
      tags:
        - Vote
      description: Send new vote to judge
      requestBody:
        description: Body needed to submit a vote
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateVoteRequest'
        required: true
      responses:
        201:
          description: Vote submitted
          content:
            applicaction/json:
              schema:
                $ref: '#/components/schemas/Vote'
        4XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Route not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /election/getOptions:
    get:
      tags:
        - Options
      description: Request election options
      responses:
        200:
          description: Return all the Options
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Options'
        4XX:
          description: Options not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Options not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /election/getResults:
    get:
      tags:
        - Results
      description: Request election results
      responses:
        200:
          description: Return the results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
        4XX:
          description: Results not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Results not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        201:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          description: The id of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  schemas:

    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress

    Voter:
      type: object
      properties:
        voterId: 
          type: string

    Vote:
      type: object
      properties:
        nonceId:
          type: string
        encryptedVote:
          type: array  # REVISAR 
        electionId:
          type: string
        clientPublicKey:
          type: array # REVISAR 

    Options:
      type: object
      properties:
        name:
          type: string
        date_birth: 
          type: string ## REVISAR
        number:
          type: string
        party:
          type: string
        background:
          type: string
        proposals:
          type: string
    
    Results:
      type: object
      properties:
        optionId:
          type: string
        results:
          type: string

    ValidateVoterRequest:
      title: Validate Voter Request Body
      required:
        - voterId
      type: object
      properties:
        voterId:
          type: string

    ValidateVoterResponse:
      title: Validate Voter Response
      type: object
      properties:
        voter: 
          type: object
        error:
          type: string

    registerVoter:
      title: Register Voter
      required:
        - voterId
        - registrarId
        - firstName
        - lastName
      type: object
      properties:
        voterId:
          type: string
        registrarId:
          type: string
        firstName:
          type: string
        lastName: 
          type: string

    CastBallotRequest:
      title: Cast Ballot Request
      required:
        - voterId
        - electionId
      type: object
      properties:
        voterId: 
          type: string
        electionId:
          type: string

    CastBallotResponse:
      title: Cast Ballot Response
      type: object
      properties:
        success: 
          type: string
        error:
          type: string
    
    ValidateVoteRequest:
      title: Validate Vote Request
      type: object
      required:
        - nonceId
        - encryptedVote
        - electionId
        - clientPublicKey
      properties:
        nonceId:
          type: string
        encryptedVote:
          type: array  # REVISAR
        electionId:
          type: string
        clientPublicKey:
          type: array  # REVISAR